name: Merge JSON array
description: Takes a JSON string and returns a YAML string
inputs:
  first:
    description: JSON string array
    required: true
  second:
    description: JSON string array
    required: true
  sensitive:
    description: Whether to mask the output
    required: false
    default: "false"
outputs:
  yaml:
    description: YAML format of the passed JSON string
runs:
  using: docker
  image: Dockerfile
